name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Verify Docker and Docker Compose
        run: |
          docker --version
          docker-compose --version

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Node.js image
        run: |
          docker-compose build
          docker images
          docker tag docker-compose-nodejs-mongodb-app:latest ${{ secrets.DOCKER_USERNAME_REPO }}/docker-compose-nodejs-mongodb:latest
          docker push ${{ secrets.DOCKER_USERNAME_REPO }}/docker-compose-nodejs-mongodb:latest

          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}  # Ensure this is correctly set in GitHub Secrets
         # script: |
          #  docker pull ${{ secrets.DOCKER_USERNAME }}/docker-compose-nodejs-mongodb-app:latest
          # docker-compose up -d
          
      
